/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart {
  'createdAt' : Time,
  'updatedAt' : Time,
  'items' : Array<CartItem>,
}
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Product {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'stockCount' : bigint,
  'imageUrl' : string,
  'category' : string,
  'brand' : string,
  'rating' : number,
  'price' : bigint,
}
export interface ProductUpdate {
  'title' : string,
  'description' : string,
  'stockCount' : bigint,
  'imageUrl' : string,
  'category' : string,
  'brand' : string,
  'rating' : number,
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'addToCallerCart' : ActorMethod<[bigint, bigint], undefined>,
  'addToCart' : ActorMethod<[Principal, bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCallerCart' : ActorMethod<[], undefined>,
  'clearCart' : ActorMethod<[Principal], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerCart' : ActorMethod<[], Cart>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[Principal], Cart>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsFiltered' : ActorMethod<[[] | [string]], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCallerCart' : ActorMethod<[bigint], undefined>,
  'removeFromCart' : ActorMethod<[Principal, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCallerCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'updateCartItem' : ActorMethod<[Principal, bigint, bigint], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductUpdate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];